import { getNetworkConfig } from './networkConfig';

// Placeholder for axionvera-sdk if it existed, we mock the behavior for now.
// In a real-world scenario, you would import the contract client generated by Soroban CLI or Axionvera SDK.
import { Contract, SorobanRpc } from '@stellar/stellar-sdk';

export const VAULT_CONTRACT_ID = process.env.NEXT_PUBLIC_VAULT_CONTRACT_ID || 'CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';

export const getVaultContract = () => {
  const config = getNetworkConfig();
  const server = new SorobanRpc.Server(config.rpcUrl);
  return new Contract(VAULT_CONTRACT_ID);
};

export const formatBalance = (balance: string | number, decimals: number = 7): string => {
  const num = typeof balance === 'string' ? parseFloat(balance) : balance;
  return (num / Math.pow(10, decimals)).toFixed(decimals);
};

export const parseAmount = (amount: string, decimals: number = 7): string => {
  const num = parseFloat(amount);
  return (num * Math.pow(10, decimals)).toString();
};
